http://localhost:3000/cursos

###
//GET de curso específico
GET http://localhost:3000/cursos/1

###
//CRIAR
POST  http://localhost:3000/cursos/ HTTP/1.1
content-type: application/json


###
//ATUALIZAR
PUT http://localhost:3000/cursos/2 HTTP/1.1
content-type: application/json


###

DELETE   http://localhost:3000/cursos/2
